name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main ブランチへのプッシュ時に自動デプロイ
  workflow_dispatch: # 手動でワークフローを実行できるようにする

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest # ビルド環境を指定
    name: Build and Deploy to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # あなたのNuxt.jsプロジェクトのNode.jsバージョンに合わせる

      - name: Install dependencies
        # サブディレクトリでnpm installを実行
        run: npm install 
        working-directory: ./metrics-viewer # ★ここを追加

      - name: Fetch GitHub Data at Build Time 
        # サブディレクトリでスクリプトを実行
        run: node ./scripts/fetch-github-data.js
        working-directory: ./metrics-viewer # ★ここを追加
        env:
          NUXT_GITHUB_TOKEN: ${{ secrets.NUXT_GITHUB_TOKEN_SECRET }} 

      - name: Build Nuxt.js project
        # サブディレクトリでnpm run buildを実行
        run: npm run build 
        working-directory: ./metrics-viewer # ★ここを追加

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # デプロイするディレクトリもサブディレクトリ内のビルド成果物パスに変更
          # 例: metrics-viewer/.output/public
          publish_dir: ./metrics-viewer/.output/public # ★ここも修正
          # cname: example.com # 必要であればカスタムドメインを設定